#!/bin/sh

# Disable globbing, e.g. "*".
set -f

set -- $SSH_ORIGINAL_COMMAND
if [ "$1" = "age-plugin-se" ]; then
	shift
	exec /nix/var/nix/profiles/default/bin/nix run nixpkgs#age-plugin-se -- "$@"
fi
if [ "$1" = "age-plugin-yubikey" ]; then
	shift
	export LC_ALL=en_US.UTF-8
	exec /nix/var/nix/profiles/default/bin/nix run nixpkgs#age-plugin-yubikey -- "$@"
fi

exit 22
