#!/bin/sh

set -eu

cd ~/.ssh/ephemeral_sshd/

if [ ! -f ssh_host_ed25519_key ]; then
  echo "Host key missing, generating..."
  ssh-keygen -q -t ed25519 -f ssh_host_ed25519_key -N ''
  rm -f ssh_host_ed25519_key.pub
fi

if [ ! -f authorized_keys ]; then
  echo "Client key missing, generating..."
  ssh-keygen -q -t ed25519 -f id_ed25519 -N ''
  mv id_ed25519.pub authorized_keys
  echo "Put id_ed25519 into ~/.ssh/id_ed25519_reverse_ssh on the server"
fi

echo "Starting SSH server with fingerprint:"
ssh-keygen -lf ssh_host_ed25519_key
exec /usr/sbin/sshd -f sshd_config -D -e
