
set  -g default-terminal "screen"
set  -g base-index      0
setw -g pane-base-index 0





set -g status-keys vi
set -g mode-keys   vi

bind -N "Select pane to the left of the active pane" h select-pane -L
bind -N "Select pane below the active pane" j select-pane -D
bind -N "Select pane above the active pane" k select-pane -U
bind -N "Select pane to the right of the active pane" l select-pane -R

bind -r -N "Resize the pane left by 5" \
  H resize-pane -L 5
bind -r -N "Resize the pane down by 5" \
  J resize-pane -D 5
bind -r -N "Resize the pane up by 5" \
  K resize-pane -U 5
bind -r -N "Resize the pane right by 5" \
  L resize-pane -R 5


# rebind main key: C-a
unbind C-b
set -g prefix C-a
bind -N "Send the prefix key through to the application" \
  C-a send-prefix




set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  12
set  -s escape-time       0
set  -g history-limit     10240

set-environment -g SSH_AUTH_SOCK $HOME/.ssh/ssh_auth_sock
set-option -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION"

# Instead of flashing or beeping, blink the window in status.
set -g visual-bell off
set -g monitor-activity on
set -g bell-action none
set -g window-status-activity-style "fg=yellow,blink"

# Requires support from terminal (e.g. iTerm2).
set -s set-clipboard on

# For scrolling through logs.
bind y set-window-option synchronize-panes

# Panel configuration.
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind Enter resize-pane -Z

# Navigation.
bind -n M-Up new-window -c "#{pane_current_path}"
bind -n M-Down confirm-before -p "kill-window #W? (y/n)" kill-window
bind -n M-Left previous-window
bind -n M-Right next-window

# Status bar.
set -g status-interval 5
set -g status-position bottom
set -g status-style "bg=default,fg=white"

set -g status-left-length 20
set -g status-left "#[fg=green,bold]#H #[fg=white]| "

set -g status-right-length 60
set -g status-right "#[fg=cyan]%H:%M%Z %d.%m.%Y #[fg=white]| #[fg=yellow]Load: #(cut -d ' ' -f 1-3 /proc/loadavg)"

set -g status-justify left
set -g window-status-format "#[fg=white,dim]#I:#W#F"
set -g window-status-current-format "#[fg=white,bold,bg=blue] #I:#W#F "
